
package com.yucheng.cmis.retailloan.ws.stage.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-11T18:45:20.345+08:00
 * Generated source version: 3.1.16
 */

@WebFault(name = "Exception", targetNamespace = "http://service.stage.ws.retailloan.cmis.yucheng.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.yucheng.cmis.retailloan.ws.stage.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.yucheng.cmis.retailloan.ws.stage.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.yucheng.cmis.retailloan.ws.stage.service.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.yucheng.cmis.retailloan.ws.stage.service.Exception getFaultInfo() {
        return this.exception;
    }
}
