
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.yucheng.cmis.retailloan.ws.stage.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-11T18:45:20.360+08:00
 * Generated source version: 3.1.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "MerchantSupplyServiceWS",
                      portName = "MerchantSupplyServiceImplWSPort",
                      targetNamespace = "http://impl.service.stage.ws.retailloan.cmis.yucheng.com/",
                      wsdlLocation = "http://10.8.198.72:9001/maps/ws/merchantSupplyServiceWS?WSDL",
                      endpointInterface = "com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS")
                      
public class MerchantSupplyServiceImplWSPortImpl implements IMerchantSupplyServiceWS {

    private static final Logger LOG = Logger.getLogger(MerchantSupplyServiceImplWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS#merchantReSubmit(java.lang.String reSubmitData)*
     */
    public java.lang.String merchantReSubmit(java.lang.String reSubmitData) throws Exception_Exception   { 
        LOG.info("Executing operation merchantReSubmit");
        System.out.println(reSubmitData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS#merchantModify(java.lang.String modifyData)*
     */
    public java.lang.String merchantModify(java.lang.String modifyData) throws Exception_Exception   { 
        LOG.info("Executing operation merchantModify");
        System.out.println(modifyData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS#merchantQuery(java.lang.String queryData)*
     */
    public java.lang.String merchantQuery(java.lang.String queryData) throws Exception_Exception   { 
        LOG.info("Executing operation merchantQuery");
        System.out.println(queryData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS#queryMerchantStageStatus(java.lang.String statusInfo)*
     */
    public java.lang.String queryMerchantStageStatus(java.lang.String statusInfo) throws Exception_Exception   { 
        LOG.info("Executing operation queryMerchantStageStatus");
        System.out.println(statusInfo);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.yucheng.cmis.retailloan.ws.stage.service.IMerchantSupplyServiceWS#merchantApply(java.lang.String applyData)*
     */
    public java.lang.String merchantApply(java.lang.String applyData) throws Exception_Exception   { 
        LOG.info("Executing operation merchantApply");
        System.out.println(applyData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
